// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";
  var nonAsyncCount, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  nonAsyncCount = 0;

  root.asyncExecute = function(fn) {
    if ((typeof document !== "undefined" && document !== null) && (document.hidden || document.mozHidden || document.webkitHidden || document.msHidden) && nonAsyncCount++ < 10000) {
      return fn();
    } else {
      nonAsyncCount = 0;
      return setImmediate(fn);
    }
  };

}).call(this);
